### ISSUE TITLE
Catch-all mailbox

### ISSUE THREAD

**Issue by skromberg** [bhopmann/uberspace7-mailfilter#3]
If you use a catchall mailbox with uberspace, the emails are not assigned correctly:

```bash
uberspace mail user list
+
test1
test2
```

Since there will always be only [one](https://manual.uberspace.de/en/mail-mailboxes.html) catchall-mail, the assignment of mailbox (test1) and catchall (+) as new configuration parameter in e.g. .mailfilter[<namespace>] would be a solution

Alternatively the mailbox can be read via `uberspace mail catchall status`

**Comment by darkmattercoder** [comment]
I have catchall on uberspace for more than 8 years and the scripts work fine for me. However, when I issue `uberspace mail catchall status`, it says that no catchall was configured. But normally an explicit catchall configuration is not necessary at all, since it ist the default anyway. The above `mail user list` returns a `listvdomain: can't open password table`

I suspect that this all has to do with me not having setup separate mailboxes but instead use solely filtering via maildrop to different maildirs

**Comment by skromberg** [comment]
> I have catchall on uberspace for more than 8 years and the scripts work fine for me. However, when I issue `uberspace mail catchall status`, it says that no catchall was configured. But normally an explicit catchall configuration is not necessary at all, since it ist the default anyway. The above `mail user list` returns a `listvdomain: can't open password table`
> 
> I suspect that this all has to do with me not having setup separate mailboxes but instead use solely filtering via maildrop to different maildirs

The last seven years on U6 with a corresponding script have also worked well for me. With the switch to U7 and the new script the problem has come up. The [original scripts](https://manual.uberspace.de/mail-spam.html) from uberspace forward catchall mails correctly.

**Comment by darkmattercoder** [comment]
I assume then it is only the case if you set up multiple user mailboxes. If you only work with the system mailbox, the scripts work well on U7.

**Comment by bhopmann** [comment]
Thank you for your hints and discussion, @skromberg and @darkmattercoder . You are welcome to send a fix for it, since I neither use a catchall mailbox (I've set up two mailboxes) nor the Uberspace Spam script.
