### ISSUE TITLE
dumpvuser: No such user

### ISSUE THREAD

**Issue by mokorana** [bhopmann/uberspace7-mailfilter#5]
If spam-learn is executed and found new spam I receive a mail with the message: 

> dumpvuser: No such user

It seems there is a conflict between `:` and `.` in my dumpvuser. My Name is `firstname.lastname` but my directory is `./users/firstname:lastname` as explained here https://wiki.uberspace.de/mail:dotqmail

My question is now if this is something the script is not aware of or do / can I adjust my qmail-configuration?

**Comment by bhopmann** [comment]
The script `.mailfilters/checkmaildir` checks, wether it is called from a .qmail-EXT instead of .qmail and it check if a vmailmgr user named $EXT does exist (via `dumpvuser $EXT | grep '^Directory' | awk '{ print $2 }'`). So, it is not aware of your configuration with two different names. And of course you can adjust your qmail-configuration by removing `:` and `.` (but bewarem this could have side effects on you email configuration).

**Comment by mokorana** [comment]
Thanks! I am just wondering because http://www.lifewithqmail.org/lwq.html#dots-in-extensions says 

> G.4. qmail replaces dots (.) in extension addresses with colons (:).

I guess that means I have to change my dumpvuser Name from `.` to `:`

**Comment by bhopmann** [comment]
Let me know if that helps:

> I guess that means I have to change my dumpvuser Name from `.` to `:`

**Comment by mokorana** [comment]
I checked my qmail-configuration but it seems fine. When I setup a new mailbox `uberspace mail user add firstname.lastname` the same "error" appears.

When I receive a new mail `.mailfilters/checkmaildir` seems to be working perfectly. However, using `spam-learn` the `$EXT` seems to be wrong or to be more precise the `:` is not auto-replaced by an `.`

See #8

**Comment by bhopmann** [comment]
Thank you for this PR – this seems to work also for other mailbox without an `.` so far.
